import React, { useState, useEffect, useRef } from "react";
import { useLocation } from "react-router-dom";
import { jsPDF } from "jspdf";
import { logoBase64 } from "./logo";

/* =========================================
   CONSTANTS & LEGAL DATA
========================================= */
const ONTARIO_GUIDELINE_2025 = 2.5;

const UI = {
  en: {
    title: "CAPtenant Letter Generator",
    labelInput: "Draft your letter or review transported notes:",
    labelTone: "Tone:",
    btnRewrite: "Generate / Rewrite Letter",
    placeholder: "Type your notes here...",
    working: "CAPtenant AI is working...",
    subject: "Subject",
    signature: "Tenant Signature",
    rightsTip: "Know your rights:",
    fromVoice: "Generated from Voice Assistant",
    fromAgi: "Generated from AGI Explainer",
    agiWarning: "⚖️ Legal Notice: Rent increase exceeds the guideline.",
    download: "Download PDF",
    legalRefs: "Relevant Legal Context (Ontario)"
  },
  fr: {
    title: "Générateur de lettres CAPtenant",
    labelInput: "Rédigez votre lettre ou révisez les notes transférées :",
    labelTone: "Ton :",
    btnRewrite: "Générer / Réécrire la lettre",
    placeholder: "Tapez vos notes ici...",
    working: "L'IA de CAPtenant travaille...",
    subject: "Objet",
    signature: "Signature du locataire",
    rightsTip: "Connaissez vos droits :",
    fromVoice: "Généré par l'assistant vocal",
    fromAgi: "Généré par l'outil AGI",
    agiWarning: "⚖️ Avis juridique : l’augmentation dépasse la ligne directrice.",
    download: "Télécharger le PDF",
    legalRefs: "Contexte juridique pertinent (Ontario)"
  }
};

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:3001";

export default function LetterGenerator() {
  const location = useLocation();
  const params = new URLSearchParams(location.search);

  /* 🇨🇦 Language detection */
  const rawLang = params.get("lang") || "en";
  const isFrench = rawLang.toLowerCase().startsWith("fr");
  const lang = isFrench ? "fr" : "en";
  const t = UI[lang];
  const letterLanguage = isFrench ? "fr-CA" : "en-CA";

  /* --- STATE --- */
  const [inputText, setInputText] = useState("");
  const [style, setStyle] = useState("professional");
  const [rewritten, setRewritten] = useState("");
  const [subjectLine, setSubjectLine] = useState("");
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [isAboveGuideline, setIsAboveGuideline] = useState(false);
  const [aboveGuidelinePercent, setAboveGuidelinePercent] = useState(null);

  const autoGeneratedRef = useRef(false);
  const fromSource = params.get("from");
  const incomingIntent = (params.get("intent") || "").toLowerCase();

  /* =========================================
      INIT FROM QUERY (VOICE / AGI)
  ========================================= */
  useEffect(() => {
    const agi = Number(params.get("agiPercent"));
    if (agi > ONTARIO_GUIDELINE_2025) {
      setIsAboveGuideline(true);
      setAboveGuidelinePercent((agi - ONTARIO_GUIDELINE_2025).toFixed(2));
    }

    const summary = params.get("summary") || params.get("agiSummary") || "";
    const tone = params.get("agiTone") || "professional";

    if (summary && !inputText) {
      setInputText(summary);
      setStyle(tone);
    }

    if (summary && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      callRewriteAPI(summary, tone);
    }
  }, [location.search]);

  /* =========================================
      RIGHTS TIP 
  ========================================= */
  const getRightsTip = () => {
    const lower = inputText.toLowerCase();
    const raw = inputText || "";

    if (
      lower.includes("n12") ||
      lower.includes("own use") ||
      raw.includes("إخلاء") ||
      /\bnikal(na)?\b/i.test(raw)
    ) {
      return lang === "fr"
        ? "En vertu de l’article 48, une indemnité d’un mois de loyer est requise."
        : "Under s.48, one month’s rent compensation is required.";
    }

    if (lower.includes("deposit") || raw.includes("وديعة") || lower.includes("paise")) {
      return lang === "fr"
        ? "Les dépôts pour dommages ou animaux sont interdits."
        : "Damage and pet deposits are illegal.";
    }

    return null;
  };

  /* =========================================
      SMART SUBJECT
  ========================================= */
  const generateTitle = () => {
    if (incomingIntent.includes("evict"))
      return lang === "fr"
        ? "Objet : Contestation d’expulsion"
        : "Subject: Eviction Dispute";

    if (incomingIntent.includes("repair"))
      return lang === "fr"
        ? "Objet : Demande de réparations"
        : "Subject: Request for Repairs";

    return lang === "fr"
      ? "Objet : Communication du locataire"
      : "Subject: Tenant Communication";
  };

  /* =========================================
      AI REWRITE — LETTER ONLY
  ========================================= */
  const callRewriteAPI = async (textToProcess, selectedStyle) => {
    const finalInput = textToProcess || inputText;
    if (!finalInput.trim()) return;

    setLoading(true);
    setErrorMsg("");

    const baseInstruction =
      lang === "fr"
        ? "Rédige la lettre entièrement en français canadien (fr-CA)."
        : "Write the letter entirely in Canadian English (en-CA).";

    try {
      const res = await fetch(`${API_BASE}/rewrite`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: `${baseInstruction}\n\n${finalInput}`,
          style: selectedStyle || style,
          language: letterLanguage
        })
      });

      if (!res.ok) throw new Error();
      const data = await res.json();

      setRewritten((data.rewritten || "").trim());
      setSubjectLine(generateTitle());
    } catch {
      setErrorMsg(lang === "fr" ? "Erreur de connexion." : "Could not reach CAPtenant backend.");
    } finally {
      setLoading(false);
    }
  };

  /* =========================================
      LEGAL EXCERPTS
  ========================================= */
  const renderLegalExcerpts = () => {
    const raw = inputText || "";
    const isEviction =
      incomingIntent.includes("evict") ||
      raw.includes("إخلاء") ||
      /\bnikal(na)?\b/i.test(raw) ||
      /sans préavis|without notice/i.test(raw);

    if (!isEviction) return null;

    return (
      <div
        style={{
          marginTop: "2rem",
          padding: "1rem",
          background: "#f1f3f5",
          borderLeft: "5px solid #0d6efd",
          borderRadius: "6px",
          fontSize: "0.95rem"
        }}
      >
        <strong>{t.legalRefs}</strong>
        <ul style={{ marginTop: "0.5rem" }}>
          <li><strong>s. 24</strong> — {lang === "fr"
            ? "Les expulsions illégales et les changements de serrure sont interdits."
            : "Illegal lockouts are prohibited."}</li>
          <li><strong>s. 43</strong> — {lang === "fr"
            ? "L’accès au logement exige un avis valide."
            : "Entry requires proper notice."}</li>
          <li><strong>s. 48</strong> — {lang === "fr"
            ? "Conditions d’expulsion pour usage personnel (N12)."
            : "N12 / own-use eviction requirements."}</li>
          <li><strong>s. 83</strong> — {lang === "fr"
            ? "La CLI peut refuser une expulsion même valide."
            : "LTB discretion to refuse eviction."}</li>
        </ul>
      </div>
    );
  };

  /* =========================================
      PDF GENERATION (FIXED)
  ========================================= */
  const downloadAsPDF = () => {
    if (!rewritten) return;

    try {
      const doc = new jsPDF();
      let y = 20;

      // 1. Add Logo if valid
      if (logoBase64 && logoBase64.startsWith("data:image")) {
        try {
          doc.addImage(logoBase64, "PNG", 15, y, 30, 30);
          y += 40;
        } catch (e) {
          console.warn("Logo image failed to load in PDF", e);
          y += 10; // Fallback spacing
        }
      }

      // 2. Add Subject Line
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      const title = subjectLine || (lang === "fr" ? "Communication" : "Communication");
      doc.text(title, 15, y);
      y += 12;

      // 3. Add Letter Content
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      
      const lines = doc.splitTextToSize(rewritten, 180);
      
      // Handle simple page overflow for long letters
      lines.forEach(line => {
        if (y > 280) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, 15, y);
        y += 7;
      });

      // 4. Add Signature line
      y += 15;
      if (y > 280) { doc.addPage(); y = 20; }
      doc.text("______________________________", 15, y);
      y += 7;
      doc.setFont("helvetica", "italic");
      doc.text(t.signature, 15, y);

      // 5. Save
      doc.save(`CAPtenant_Letter_${Date.now()}.pdf`);
    } catch (err) {
      console.error("PDF Generation Error:", err);
      alert(lang === "fr" ? "Erreur lors de la création du PDF." : "Error creating PDF.");
    }
  };

  /* =========================================
      RENDER
  ========================================= */
  return (
    <div style={{ padding: "2rem", maxWidth: "900px", margin: "auto" }}>
      <h1>{t.title}</h1>

      {fromSource && (
        <div style={{ background: "#eef6ff", padding: "12px", marginBottom: "1rem" }}>
          <strong>{fromSource === "agi" ? t.fromAgi : t.fromVoice}</strong>
        </div>
      )}

      <textarea
        value={inputText}
        onChange={(e) => setInputText(e.target.value)}
        placeholder={t.placeholder}
        style={{ width: "100%", height: "180px", padding: "12px" }}
      />

      <div style={{ marginTop: "1rem" }}>
        <select value={style} onChange={(e) => setStyle(e.target.value)}>
          {["professional", "polite", "firm", "urgent"].map(s => (
            <option key={s}>{s}</option>
          ))}
        </select>

        <button
          onClick={() => callRewriteAPI()}
          disabled={loading}
          style={{
            marginLeft: "10px",
            padding: "10px 20px",
            background: "#0d6efd",
            color: "white",
            border: "none",
            borderRadius: "6px",
            fontWeight: "bold",
            cursor: "pointer"
          }}
        >
          {loading ? t.working : t.btnRewrite}
        </button>
      </div>

      {errorMsg && <p style={{ color: "red" }}>{errorMsg}</p>}

      {getRightsTip() && (
        <div style={{ background: "#fff4d2", padding: "10px", marginTop: "1rem" }}>
          <strong>{t.rightsTip}</strong> {getRightsTip()}
        </div>
      )}

      {rewritten && (
        <>
          <pre style={{ 
            marginTop: "2rem", 
            whiteSpace: "pre-wrap", 
            background: "#fff", 
            padding: "20px", 
            border: "1px solid #ddd" 
          }}>
            {rewritten}
          </pre>
          
          {renderLegalExcerpts()}
          
          <button
            onClick={downloadAsPDF}
            style={{
              marginTop: "1.5rem",
              padding: "14px 28px",
              background: "#28a745",
              color: "white",
              border: "none",
              borderRadius: "6px",
              fontWeight: "bold",
              minWidth: "220px",
              cursor: "pointer"
            }}
          >
            📄 {t.download}
          </button>
        </>
      )}
    </div>
  );
}