import React, { useState, useEffect, useRef } from "react";
import { useLocation } from "react-router-dom";
import { jsPDF } from "jspdf";
import { logoBase64 } from "./logo";

/* =========================================
   CONSTANTS & REGULATORY DATA
========================================= */
const ONTARIO_GUIDELINE_2025 = 2.5;

const UI = {
  en: {
    title: "CAPtenant Letter Generator",
    labelInput: "Draft your letter or review imported notes:",
    labelTone: "Tone:",
    btnRewrite: "Generate / Rewrite Letter",
    placeholder: "Type your notes here...",
    working: "CAPtenant is generating your letter...",
    subject: "Subject",
    signature: "Tenant Signature",
    rightsTip: "Helpful information:",
    fromVoice: "Generated from Voice Assistant",
    fromAgi: "Generated from AGI Explainer",
    agiWarning:
      "⚠️ Notice: The increase described exceeds Ontario’s annual guideline.",
    download: "Download PDF",
    refsTitle: "Relevant Ontario Rental Rules (Informational)"
  },
  fr: {
    title: "Générateur de lettres CAPtenant",
    labelInput:
      "Rédigez votre lettre ou révisez les notes importées :",
    labelTone: "Ton :",
    btnRewrite: "Générer / Réécrire la lettre",
    placeholder: "Tapez vos notes ici...",
    working: "CAPtenant génère votre lettre...",
    subject: "Objet",
    signature: "Signature du locataire",
    rightsTip: "Information utile :",
    fromVoice: "Généré par l’assistant vocal",
    fromAgi: "Généré par l’outil AGI",
    agiWarning:
      "⚠️ Avis : l’augmentation décrite dépasse la ligne directrice annuelle.",
    download: "Télécharger le PDF",
    refsTitle: "Règles locatives pertinentes en Ontario (information)"
  }
};

/* =========================
   🔌 BACKEND
========================= */
const API_BASE =
  import.meta.env.VITE_API_URL ??
  "https://captenant-production.up.railway.app";

export default function LetterGenerator() {
  const location = useLocation();
  const params = new URLSearchParams(location.search);

  /* 🇨🇦 Language lock */
  const rawLang = params.get("lang") || "en";
  const isFrench = rawLang.toLowerCase().startsWith("fr");
  const lang = isFrench ? "fr" : "en";
  const t = UI[lang];
  const letterLanguage = isFrench ? "fr-CA" : "en-CA";

  /* --- STATE --- */
  const [inputText, setInputText] = useState("");
  const [style, setStyle] = useState("professional");
  const [rewritten, setRewritten] = useState("");
  const [subjectLine, setSubjectLine] = useState("");
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [isAboveGuideline, setIsAboveGuideline] = useState(false);
  const [aboveGuidelinePercent, setAboveGuidelinePercent] = useState(null);

  const autoGeneratedRef = useRef(false);
  const fromSource = params.get("from");
  const incomingIntent = (params.get("intent") || "").toLowerCase();

  /* =========================================
      INIT FROM QUERY (VOICE / AGI)
  ========================================= */
  useEffect(() => {
    const agi = Number(params.get("agiPercent"));
    if (agi > ONTARIO_GUIDELINE_2025) {
      setIsAboveGuideline(true);
      setAboveGuidelinePercent(
        (agi - ONTARIO_GUIDELINE_2025).toFixed(2)
      );
    }

    const summary =
      params.get("summary") || params.get("agiSummary") || "";
    const tone = params.get("agiTone") || "professional";

    if (summary && !inputText) {
      setInputText(summary);
      setStyle(tone);
    }

    if (summary && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      callRewriteAPI(summary, tone);
    }
  }, [location.search]);

  /* =========================================
      HELPFUL INFO TIP (SAFE)
  ========================================= */
  const getRightsTip = () => {
    const lower = inputText.toLowerCase();
    const raw = inputText || "";

    if (
      lower.includes("n12") ||
      lower.includes("own use") ||
      raw.includes("إخلاء") ||
      /\bnikal(na)?\b/i.test(raw)
    ) {
      return lang === "fr"
        ? "Dans certains cas, une compensation équivalente à un mois de loyer peut être requise."
        : "In some cases, compensation equal to one month’s rent may be required.";
    }

    if (
      lower.includes("deposit") ||
      raw.includes("وديعة") ||
      lower.includes("paise")
    ) {
      return lang === "fr"
        ? "Les dépôts pour dommages ou animaux ne sont généralement pas permis."
        : "Damage and pet deposits are generally not permitted.";
    }

    return null;
  };

  /* =========================================
      SUBJECT LINE
  ========================================= */
  const generateTitle = () => {
    if (incomingIntent.includes("evict"))
      return lang === "fr"
        ? "Objet : Contestation d’expulsion"
        : "Subject: Eviction Concern";

    if (incomingIntent.includes("repair"))
      return lang === "fr"
        ? "Objet : Demande de réparations"
        : "Subject: Request for Repairs";

    return lang === "fr"
      ? "Objet : Communication du locataire"
      : "Subject: Tenant Communication";
  };

  /* =========================================
      AI REWRITE — LETTER CONTENT ONLY
  ========================================= */
  const callRewriteAPI = async (
    textToProcess,
    selectedStyle
  ) => {
    const finalInput = textToProcess || inputText;
    if (!finalInput.trim()) return;

    setLoading(true);
    setErrorMsg("");

    const baseInstruction =
      lang === "fr"
        ? "Rédige la lettre entièrement en français canadien (fr-CA)."
        : "Write the letter entirely in Canadian English (en-CA).";

    try {
      const res = await fetch(`${API_BASE}/rewrite`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: `${baseInstruction}\n\n${finalInput}`,
          style: selectedStyle || style,
          language: letterLanguage
        })
      });

      if (!res.ok) throw new Error();
      const data = await res.json();

      setRewritten((data.rewritten || "").trim());
      setSubjectLine(generateTitle());
    } catch {
      setErrorMsg(
        lang === "fr"
          ? "Impossible de joindre le service CAPtenant."
          : "Unable to reach CAPtenant service."
      );
    } finally {
      setLoading(false);
    }
  };

  /* =========================================
      INFORMATIONAL REFERENCES (SAFE)
  ========================================= */
  const renderInfoRefs = () => {
    const raw = inputText || "";
    const isEviction =
      incomingIntent.includes("evict") ||
      raw.includes("إخلاء") ||
      /\bnikal(na)?\b/i.test(raw) ||
      /sans préavis|without notice/i.test(raw);

    if (!isEviction) return null;

    return (
      <div
        style={{
          marginTop: "2rem",
          padding: "1rem",
          background: "#f1f3f5",
          borderLeft: "5px solid #0d6efd",
          borderRadius: "6px",
          fontSize: "0.95rem"
        }}
      >
        <strong>{t.refsTitle}</strong>
        <ul style={{ marginTop: "0.5rem" }}>
          <li>Restrictions on lockouts</li>
          <li>Notice requirements for entry</li>
          <li>Conditions for own-use notices</li>
          <li>Board discretion in eviction outcomes</li>
        </ul>
      </div>
    );
  };

  /* =========================================
      PDF GENERATION (UNCHANGED STRUCTURE)
  ========================================= */
  const downloadAsPDF = () => {
    if (!rewritten) return;

    try {
      const doc = new jsPDF();
      let y = 20;

      if (logoBase64 && logoBase64.startsWith("data:image")) {
        try {
          doc.addImage(logoBase64, "PNG", 15, y, 30, 30);
          y += 40;
        } catch {
          y += 10;
        }
      }

      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(subjectLine || "Communication", 15, y);
      y += 12;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(rewritten, 180);

      lines.forEach((line) => {
        if (y > 280) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, 15, y);
        y += 7;
      });

      y += 15;
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text("______________________________", 15, y);
      y += 7;
      doc.setFont("helvetica", "italic");
      doc.text(t.signature, 15, y);

      doc.save(`CAPtenant_Letter_${Date.now()}.pdf`);
    } catch {
      alert(
        lang === "fr"
          ? "Erreur lors de la création du PDF."
          : "Error creating PDF."
      );
    }
  };

  /* =========================================
      RENDER
  ========================================= */
  return (
    <div style={{ padding: "2rem", maxWidth: "900px", margin: "auto" }}>
      <h1>{t.title}</h1>

      {fromSource && (
        <div
          style={{
            background: "#eef6ff",
            padding: "12px",
            marginBottom: "1rem"
          }}
        >
          <strong>
            {fromSource === "agi" ? t.fromAgi : t.fromVoice}
          </strong>
        </div>
      )}

      <textarea
        value={inputText}
        onChange={(e) => setInputText(e.target.value)}
        placeholder={t.placeholder}
        style={{ width: "100%", height: "180px", padding: "12px" }}
      />

      <div style={{ marginTop: "1rem" }}>
        <select
          value={style}
          onChange={(e) => setStyle(e.target.value)}
        >
          {["professional", "polite", "firm", "urgent"].map((s) => (
            <option key={s}>{s}</option>
          ))}
        </select>

        <button
          onClick={() => callRewriteAPI()}
          disabled={loading}
          style={{
            marginLeft: "10px",
            padding: "10px 20px",
            background: "#0d6efd",
            color: "white",
            border: "none",
            borderRadius: "6px",
            fontWeight: "bold",
            cursor: "pointer"
          }}
        >
          {loading ? t.working : t.btnRewrite}
        </button>
      </div>

      {errorMsg && <p style={{ color: "red" }}>{errorMsg}</p>}

      {getRightsTip() && (
        <div
          style={{
            background: "#fff4d2",
            padding: "10px",
            marginTop: "1rem"
          }}
        >
          <strong>{t.rightsTip}</strong> {getRightsTip()}
        </div>
      )}

      {isAboveGuideline && (
        <div
          style={{
            marginTop: "1rem",
            color: "#b45309",
            fontWeight: "600"
          }}
        >
          {t.agiWarning}
        </div>
      )}

      {rewritten && (
        <>
          <pre
            style={{
              marginTop: "2rem",
              whiteSpace: "pre-wrap",
              background: "#fff",
              padding: "20px",
              border: "1px solid #ddd"
            }}
          >
            {rewritten}
          </pre>

          {renderInfoRefs()}

          <button
            onClick={downloadAsPDF}
            style={{
              marginTop: "1.5rem",
              padding: "14px 28px",
              background: "#28a745",
              color: "white",
              border: "none",
              borderRadius: "6px",
              fontWeight: "bold",
              minWidth: "220px",
              cursor: "pointer"
            }}
          >
            📄 {t.download}
          </button>
        </>
      )}
    </div>
  );
}
